services:
  db-api:
    image: postgres:15
    container_name: db-api
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_api_data:/var/lib/postgresql/data
    networks:
      - prod-network

  api:
    build: ./vuln-api
    container_name: api
    restart: always
    depends_on:
      - db-api
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db-api:5432/${DB_NAME}
      WAZUH_USER: ${WAZUH_USER}
      WAZUH_PASSWORD: ${WAZUH_PASSWORD}
      WAZUH_API_URL: ${WAZUH_API_URL}
      WAZUH_INDEXER_URL: ${WAZUH_INDEXER_URL}
      SECRET_KEY: ${API_SECRET_KEY}
    networks:
      - prod-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    restart: always
    depends_on:
      - api
    networks:
      - prod-network

  # 4. API Gateway (El Nginx Maestro en la raíz del proyecto)
  gateway:
    image: nginx:alpine
    container_name: gateway-prod
    restart: always
    ports:
      # ÚNICO punto de entrada a toda tu infraestructura
      - "80:80"
      # - "443:443" # Descomentar cuando agregues Certbot/SSL
    volumes:
      # Montamos el archivo maestro como solo lectura (ro)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api
    networks:
      - prod-network

volumes:
  postgres_api_data:

networks:
  prod-network:
    driver: bridge
