# =========================
# Identidad del proyecto
# =========================
sonar.projectKey=vuln-app-api
sonar.projectName=Vuln App Wazuh API

# =========================
# Código fuente
# =========================
# Analiza SOLO la API
sonar.sources=vuln-api/app
sonar.tests=vuln-api/tests

# =========================
# Lenguaje
# =========================
sonar.language=py
sonar.python.version=3.12

sonar.python.coverage.reportPaths=vuln-api/coverage.xml

# =========================
# Exclusiones
# =========================
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/reports/**

# =========================
# Encoding
# =========================
sonar.sourceEncoding=UTF-8
